version: '2'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@172.31.26.251:3306/twittor
      - MAIL_USERNAME=twittorservice123@gmail.com
      - MAIL_PASSWORD=twittoradmin123

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web
